FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.18 AS builder

WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 GOOS=${GOOS} GOPROXY=${GOPROXY} go build \
	-ldflags="-w -s -X 'main.version=${VERSION}'" \
	-o=gcp-cloud-controller-manager \
	./cmd/cloud-controller-manager

FROM registry.ci.openshift.org/ocp/4.18:base-rhel9

LABEL description="GCP Cloud Controller Manager"

COPY --from=builder /build/gcp-cloud-controller-manager /bin/gcp-cloud-controller-manager

ENTRYPOINT [ "/bin/gcp-cloud-controller-manager" ]
