version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
  - "ok-to-test"
  - 'area/dependency'
  - 'release-note-none'
- package-ecosystem: gomod
  directories:
  - "/"
  - "/providers"
  - "/metis"
  - "/test/e2e"
  schedule:
    interval: weekly
  labels:
  - 'area/dependency'
  - 'release-note-none'
  - 'ok-to-test'
  groups:
    k8s-dependencies:
      patterns:
      - "k8s.io/*"
      - "sigs.k8s.io/*"
    workspace-deps:
      patterns:
        - "*"
      exclude-patterns:
        - "k8s.io/*"
        - "sigs.k8s.io/*"


