defaultPlatforms:
- linux/arm64
- linux/amd64

builds:
- id: cloud-controller-manager
  dir: .
  main: cmd/cloud-controller-manager
  ldflags:
  - -X k8s.io/component-base/version/verflag.programName=cloud-controller-manager
  - -X k8s.io/component-base/version.buildDate={{.Env.BUILD_DATE}}
  - -X k8s.io/component-base/version.gitCommit={{.Env.KUBE_GIT_COMMIT}}
  - -X k8s.io/component-base/version.gitTreeState={{.Env.KUBE_GIT_TREE_STATE}}
  - -X k8s.io/component-base/version.gitVersion={{.Env.KUBE_GIT_VERSION}}
- id: auth-provider-gcp
  dir: .
  main: cmd/auth-provider-gcp
  ldflags:
  - -X k8s.io/component-base/version/verflag.programName=auth-provider-gcp
  - -X k8s.io/component-base/version.buildDate={{.Env.BUILD_DATE}}
  - -X k8s.io/component-base/version.gitCommit={{.Env.KUBE_GIT_COMMIT}}
  - -X k8s.io/component-base/version.gitTreeState={{.Env.KUBE_GIT_TREE_STATE}}
  - -X k8s.io/component-base/version.gitVersion={{.Env.KUBE_GIT_VERSION}}
- id: gke-gcloud-auth-plugin
  dir: .
  main: cmd/gke-gcloud-auth-plugin
  ldflags:
  - -X k8s.io/component-base/version/verflag.programName=gke-gcloud-auth-plugin
  - -X k8s.io/component-base/version.buildDate={{.Env.BUILD_DATE}}
  - -X k8s.io/component-base/version.gitCommit={{.Env.KUBE_GIT_COMMIT}}
  - -X k8s.io/component-base/version.gitTreeState={{.Env.KUBE_GIT_TREE_STATE}}
  - -X k8s.io/component-base/version.gitVersion={{.Env.KUBE_GIT_VERSION}}