# See https://cloud.google.com/cloud-build/docs/build-config
# For more information about Image pushing refer to https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md
timeout: 3600s

options:
  substitution_option: ALLOW_LOOSE

steps:
  - name: 'gcr.io/cloud-builders/bazel'
    env:
    - IMAGE_REGISTRY=gcr.io
    - IMAGE_REPO=k8s-staging-cloud-provider-gcp
    - IMAGE_TAG=$_PULL_BASE_REF
    args:
      - run
      - //cmd/cloud-controller-manager:publish
  # TODO: use a better way to publish the same image
  # using two tags: current SHA and :latest
  - name: 'gcr.io/cloud-builders/bazel'
    env:
    - IMAGE_REGISTRY=gcr.io
    - IMAGE_REPO=k8s-staging-cloud-provider-gcp
    - IMAGE_TAG=latest
    args:
      - run
      - //cmd/cloud-controller-manager:publish

substitutions:
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'master'

tags:
- 'cloud-controller-manager'
- $_GIT_TAG
