# See https://cloud.google.com/cloud-build/docs/build-config
# For more information about Image pushing refer to https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md
timeout: 3600s
options:
  substitution_option: ALLOW_LOOSE
  machineType: E2_HIGHCPU_32
steps:
  - name: "gcr.io/cloud-builders/docker"
    env:
      - IMAGE_REPO=${_IMAGE_REPO}
      - IMAGE_TAG=${_PULL_BASE_REF}
      - CI=1
      - BUILDX_NO_DEFAULT_ATTESTATIONS=1
    entrypoint: tools/push-images
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:latest
    entrypoint: make
    args:
      - copy-binaries-to-gcs
substitutions:
  _PULL_BASE_REF: "master"
  _GIT_TAG: "12345"
  _IMAGE_REPO: "gcr.io/k8s-staging-cloud-provider-gcp"
tags:
  - "cloud-provider-gcp"
  - ${_GIT_TAG}
