load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "test",
    srcs = ["utils.go"],
    importpath = "k8s.io/cloud-provider-gcp/pkg/controller/nodeipam/ipam/test",
    visibility = ["//visibility:public"],
)
