// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: metis/api/admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_ListCIDRBlocks_FullMethodName  = "/admin.v1.Admin/ListCIDRBlocks"
	Admin_ListIPAddresses_FullMethodName = "/admin.v1.Admin/ListIPAddresses"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	ListCIDRBlocks(ctx context.Context, in *ListCIDRBlocksRequest, opts ...grpc.CallOption) (*ListCIDRBlocksResponse, error)
	ListIPAddresses(ctx context.Context, in *ListIPAddressesRequest, opts ...grpc.CallOption) (*ListIPAddressesResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ListCIDRBlocks(ctx context.Context, in *ListCIDRBlocksRequest, opts ...grpc.CallOption) (*ListCIDRBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCIDRBlocksResponse)
	err := c.cc.Invoke(ctx, Admin_ListCIDRBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListIPAddresses(ctx context.Context, in *ListIPAddressesRequest, opts ...grpc.CallOption) (*ListIPAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIPAddressesResponse)
	err := c.cc.Invoke(ctx, Admin_ListIPAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
type AdminServer interface {
	ListCIDRBlocks(context.Context, *ListCIDRBlocksRequest) (*ListCIDRBlocksResponse, error)
	ListIPAddresses(context.Context, *ListIPAddressesRequest) (*ListIPAddressesResponse, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) ListCIDRBlocks(context.Context, *ListCIDRBlocksRequest) (*ListCIDRBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCIDRBlocks not implemented")
}
func (UnimplementedAdminServer) ListIPAddresses(context.Context, *ListIPAddressesRequest) (*ListIPAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIPAddresses not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_ListCIDRBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCIDRBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListCIDRBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListCIDRBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListCIDRBlocks(ctx, req.(*ListCIDRBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListIPAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIPAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListIPAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListIPAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListIPAddresses(ctx, req.(*ListIPAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCIDRBlocks",
			Handler:    _Admin_ListCIDRBlocks_Handler,
		},
		{
			MethodName: "ListIPAddresses",
			Handler:    _Admin_ListIPAddresses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metis/api/admin/v1/admin.proto",
}
