// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metis/api/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCIDRBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCIDRBlocksRequest) Reset() {
	*x = ListCIDRBlocksRequest{}
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCIDRBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCIDRBlocksRequest) ProtoMessage() {}

func (x *ListCIDRBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCIDRBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListCIDRBlocksRequest) Descriptor() ([]byte, []int) {
	return file_metis_api_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

type GetCIDRBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCIDRBlockRequest) Reset() {
	*x = GetCIDRBlockRequest{}
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCIDRBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCIDRBlockRequest) ProtoMessage() {}

func (x *GetCIDRBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCIDRBlockRequest.ProtoReflect.Descriptor instead.
func (*GetCIDRBlockRequest) Descriptor() ([]byte, []int) {
	return file_metis_api_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetCIDRBlockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListIPAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPAddressesRequest) Reset() {
	*x = ListIPAddressesRequest{}
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPAddressesRequest) ProtoMessage() {}

func (x *ListIPAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPAddressesRequest.ProtoReflect.Descriptor instead.
func (*ListIPAddressesRequest) Descriptor() ([]byte, []int) {
	return file_metis_api_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

type GetIPAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPAddressRequest) Reset() {
	*x = GetIPAddressRequest{}
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPAddressRequest) ProtoMessage() {}

func (x *GetIPAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPAddressRequest.ProtoReflect.Descriptor instead.
func (*GetIPAddressRequest) Descriptor() ([]byte, []int) {
	return file_metis_api_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetIPAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AdminTableDumpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []string               `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminTableDumpResponse) Reset() {
	*x = AdminTableDumpResponse{}
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminTableDumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminTableDumpResponse) ProtoMessage() {}

func (x *AdminTableDumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminTableDumpResponse.ProtoReflect.Descriptor instead.
func (*AdminTableDumpResponse) Descriptor() ([]byte, []int) {
	return file_metis_api_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminTableDumpResponse) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *AdminTableDumpResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_metis_api_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *Row) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_metis_api_admin_v1_admin_proto protoreflect.FileDescriptor

const file_metis_api_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1emetis/api/admin/v1/admin.proto\x12\badmin.v1\"\x17\n" +
	"\x15ListCIDRBlocksRequest\"%\n" +
	"\x13GetCIDRBlockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16ListIPAddressesRequest\"%\n" +
	"\x13GetIPAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x16AdminTableDumpResponse\x12\x18\n" +
	"\aheaders\x18\x01 \x03(\tR\aheaders\x12!\n" +
	"\x04rows\x18\x02 \x03(\v2\r.admin.v1.RowR\x04rows\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values2\xd5\x02\n" +
	"\x05Admin\x12S\n" +
	"\x0eListCIDRBlocks\x12\x1f.admin.v1.ListCIDRBlocksRequest\x1a .admin.v1.AdminTableDumpResponse\x12O\n" +
	"\fGetCIDRBlock\x12\x1d.admin.v1.GetCIDRBlockRequest\x1a .admin.v1.AdminTableDumpResponse\x12U\n" +
	"\x0fListIPAddresses\x12 .admin.v1.ListIPAddressesRequest\x1a .admin.v1.AdminTableDumpResponse\x12O\n" +
	"\fGetIPAddress\x12\x1d.admin.v1.GetIPAddressRequest\x1a .admin.v1.AdminTableDumpResponseB#Z!k8s.io/metis/api/admin/v1;adminv1b\x06proto3"

var (
	file_metis_api_admin_v1_admin_proto_rawDescOnce sync.Once
	file_metis_api_admin_v1_admin_proto_rawDescData []byte
)

func file_metis_api_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_metis_api_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_metis_api_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metis_api_admin_v1_admin_proto_rawDesc), len(file_metis_api_admin_v1_admin_proto_rawDesc)))
	})
	return file_metis_api_admin_v1_admin_proto_rawDescData
}

var file_metis_api_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metis_api_admin_v1_admin_proto_goTypes = []any{
	(*ListCIDRBlocksRequest)(nil),  // 0: admin.v1.ListCIDRBlocksRequest
	(*GetCIDRBlockRequest)(nil),    // 1: admin.v1.GetCIDRBlockRequest
	(*ListIPAddressesRequest)(nil), // 2: admin.v1.ListIPAddressesRequest
	(*GetIPAddressRequest)(nil),    // 3: admin.v1.GetIPAddressRequest
	(*AdminTableDumpResponse)(nil), // 4: admin.v1.AdminTableDumpResponse
	(*Row)(nil),                    // 5: admin.v1.Row
}
var file_metis_api_admin_v1_admin_proto_depIdxs = []int32{
	5, // 0: admin.v1.AdminTableDumpResponse.rows:type_name -> admin.v1.Row
	0, // 1: admin.v1.Admin.ListCIDRBlocks:input_type -> admin.v1.ListCIDRBlocksRequest
	1, // 2: admin.v1.Admin.GetCIDRBlock:input_type -> admin.v1.GetCIDRBlockRequest
	2, // 3: admin.v1.Admin.ListIPAddresses:input_type -> admin.v1.ListIPAddressesRequest
	3, // 4: admin.v1.Admin.GetIPAddress:input_type -> admin.v1.GetIPAddressRequest
	4, // 5: admin.v1.Admin.ListCIDRBlocks:output_type -> admin.v1.AdminTableDumpResponse
	4, // 6: admin.v1.Admin.GetCIDRBlock:output_type -> admin.v1.AdminTableDumpResponse
	4, // 7: admin.v1.Admin.ListIPAddresses:output_type -> admin.v1.AdminTableDumpResponse
	4, // 8: admin.v1.Admin.GetIPAddress:output_type -> admin.v1.AdminTableDumpResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metis_api_admin_v1_admin_proto_init() }
func file_metis_api_admin_v1_admin_proto_init() {
	if File_metis_api_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metis_api_admin_v1_admin_proto_rawDesc), len(file_metis_api_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metis_api_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_metis_api_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_metis_api_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_metis_api_admin_v1_admin_proto = out.File
	file_metis_api_admin_v1_admin_proto_goTypes = nil
	file_metis_api_admin_v1_admin_proto_depIdxs = nil
}
