/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	networkv1 "k8s.io/cloud-provider-gcp/crd/apis/network/v1"
)

// FakeGKENetworkParams implements GKENetworkParamsInterface
type FakeGKENetworkParams struct {
	Fake *FakeNetworkingV1
}

var gkenetworkparamsResource = schema.GroupVersionResource{Group: "networking.gke.io", Version: "v1", Resource: "gkenetworkparams"}

var gkenetworkparamsKind = schema.GroupVersionKind{Group: "networking.gke.io", Version: "v1", Kind: "GKENetworkParams"}

// Get takes name of the gKENetworkParams, and returns the corresponding gKENetworkParams object, and an error if there is any.
func (c *FakeGKENetworkParams) Get(ctx context.Context, name string, options v1.GetOptions) (result *networkv1.GKENetworkParams, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(gkenetworkparamsResource, name), &networkv1.GKENetworkParams{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkv1.GKENetworkParams), err
}

// List takes label and field selectors, and returns the list of GKENetworkParams that match those selectors.
func (c *FakeGKENetworkParams) List(ctx context.Context, opts v1.ListOptions) (result *networkv1.GKENetworkParamsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(gkenetworkparamsResource, gkenetworkparamsKind, opts), &networkv1.GKENetworkParamsList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &networkv1.GKENetworkParamsList{ListMeta: obj.(*networkv1.GKENetworkParamsList).ListMeta}
	for _, item := range obj.(*networkv1.GKENetworkParamsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gKENetworkParams.
func (c *FakeGKENetworkParams) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(gkenetworkparamsResource, opts))
}

// Create takes the representation of a gKENetworkParams and creates it.  Returns the server's representation of the gKENetworkParams, and an error, if there is any.
func (c *FakeGKENetworkParams) Create(ctx context.Context, gKENetworkParams *networkv1.GKENetworkParams, opts v1.CreateOptions) (result *networkv1.GKENetworkParams, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(gkenetworkparamsResource, gKENetworkParams), &networkv1.GKENetworkParams{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkv1.GKENetworkParams), err
}

// Update takes the representation of a gKENetworkParams and updates it. Returns the server's representation of the gKENetworkParams, and an error, if there is any.
func (c *FakeGKENetworkParams) Update(ctx context.Context, gKENetworkParams *networkv1.GKENetworkParams, opts v1.UpdateOptions) (result *networkv1.GKENetworkParams, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(gkenetworkparamsResource, gKENetworkParams), &networkv1.GKENetworkParams{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkv1.GKENetworkParams), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGKENetworkParams) UpdateStatus(ctx context.Context, gKENetworkParams *networkv1.GKENetworkParams, opts v1.UpdateOptions) (*networkv1.GKENetworkParams, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(gkenetworkparamsResource, "status", gKENetworkParams), &networkv1.GKENetworkParams{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkv1.GKENetworkParams), err
}

// Delete takes name of the gKENetworkParams and deletes it. Returns an error if one occurs.
func (c *FakeGKENetworkParams) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(gkenetworkparamsResource, name), &networkv1.GKENetworkParams{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGKENetworkParams) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(gkenetworkparamsResource, listOpts)

	_, err := c.Fake.Invokes(action, &networkv1.GKENetworkParamsList{})
	return err
}

// Patch applies the patch and returns the patched gKENetworkParams.
func (c *FakeGKENetworkParams) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkv1.GKENetworkParams, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(gkenetworkparamsResource, name, pt, data, subresources...), &networkv1.GKENetworkParams{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkv1.GKENetworkParams), err
}
