// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metis/api/adaptiveipam/v1/adaptiveipam.proto

package adaptiveipam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IPConfig contains parameters required to allocate a pod IP.
type IPConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interface_name is the name of the pod interface.
	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// container_id is the id of the pod container.
	ContainerId string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// initial_pod_cidr is the CIDR block initially assigned to the node.
	// The CNI must provide this CIDR, which is used to allocate IPs for pods created
	// early in the node's lifecycle, typically including critical system pods.
	InitialPodCidr string `protobuf:"bytes,3,opt,name=initial_pod_cidr,json=initialPodCidr,proto3" json:"initial_pod_cidr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IPConfig) Reset() {
	*x = IPConfig{}
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPConfig) ProtoMessage() {}

func (x *IPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPConfig.ProtoReflect.Descriptor instead.
func (*IPConfig) Descriptor() ([]byte, []int) {
	return file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescGZIP(), []int{0}
}

func (x *IPConfig) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *IPConfig) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *IPConfig) GetInitialPodCidr() string {
	if x != nil {
		return x.InitialPodCidr
	}
	return ""
}

// AllocatePodIPRequest contains the parameters required to allocate a pod IP.
// The allocation takes into account the specified network, the initial CIDR block, and the IP family
// configuration (IPv4, IPv6, or dual-stack). If the node depletes its initial block of pod IPs,
// supplementary IPs may be dynamically acquired from the cloud provider.
// At least one of ipv4_config and ipv6_config must be populated.
type AllocatePodIPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network is the name of the network for which the IP is requested.
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// ipv4_config specifies the pod configuration for IPv4 allocation.
	Ipv4Config *IPConfig `protobuf:"bytes,2,opt,name=ipv4_config,json=ipv4Config,proto3" json:"ipv4_config,omitempty"`
	// ipv6_config specifies the pod configuration for IPv6 allocation.
	Ipv6Config *IPConfig `protobuf:"bytes,3,opt,name=ipv6_config,json=ipv6Config,proto3" json:"ipv6_config,omitempty"`
	// pod_name is the name of the pod. This is for logging purposes.
	PodName string `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// pod_namespace is the namespace of the pod. This is for logging purposes.
	PodNamespace  string `protobuf:"bytes,5,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocatePodIPRequest) Reset() {
	*x = AllocatePodIPRequest{}
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocatePodIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocatePodIPRequest) ProtoMessage() {}

func (x *AllocatePodIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocatePodIPRequest.ProtoReflect.Descriptor instead.
func (*AllocatePodIPRequest) Descriptor() ([]byte, []int) {
	return file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescGZIP(), []int{1}
}

func (x *AllocatePodIPRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *AllocatePodIPRequest) GetIpv4Config() *IPConfig {
	if x != nil {
		return x.Ipv4Config
	}
	return nil
}

func (x *AllocatePodIPRequest) GetIpv6Config() *IPConfig {
	if x != nil {
		return x.Ipv6Config
	}
	return nil
}

func (x *AllocatePodIPRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AllocatePodIPRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

// PodIP is the result of the allocated IPs for the pod.
type PodIP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ip_address is the allocated IP address.
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// cidr is the CIDR block the IP address belongs to.
	Cidr          string `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodIP) Reset() {
	*x = PodIP{}
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodIP) ProtoMessage() {}

func (x *PodIP) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodIP.ProtoReflect.Descriptor instead.
func (*PodIP) Descriptor() ([]byte, []int) {
	return file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescGZIP(), []int{2}
}

func (x *PodIP) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *PodIP) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

// AllocatePodIPResponse represents the result of a pod IP allocation request,
// detailing the assigned IPv4 and/or IPv6 addresses and their respective CIDR blocks.
type AllocatePodIPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ipv4 contains the allocated IPv4 details.
	Ipv4 *PodIP `protobuf:"bytes,1,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	// ipv6 contains the allocated IPv6 details.
	Ipv6          *PodIP `protobuf:"bytes,2,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocatePodIPResponse) Reset() {
	*x = AllocatePodIPResponse{}
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocatePodIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocatePodIPResponse) ProtoMessage() {}

func (x *AllocatePodIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocatePodIPResponse.ProtoReflect.Descriptor instead.
func (*AllocatePodIPResponse) Descriptor() ([]byte, []int) {
	return file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescGZIP(), []int{3}
}

func (x *AllocatePodIPResponse) GetIpv4() *PodIP {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *AllocatePodIPResponse) GetIpv6() *PodIP {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

// DeallocatePodIPRequest contains the parameters required to deallocate a pod IP.
type DeallocatePodIPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network is the name of the network from which the IP should be deallocated.
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// interface_name is the name of the pod interface.
	InterfaceName string `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// container_id is the id of the pod container.
	ContainerId string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// pod_name is the name of the pod. This is for logging purposes.
	PodName string `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// pod_namespace is the namespace of the pod. This is for logging purposes.
	PodNamespace  string `protobuf:"bytes,5,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeallocatePodIPRequest) Reset() {
	*x = DeallocatePodIPRequest{}
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeallocatePodIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeallocatePodIPRequest) ProtoMessage() {}

func (x *DeallocatePodIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeallocatePodIPRequest.ProtoReflect.Descriptor instead.
func (*DeallocatePodIPRequest) Descriptor() ([]byte, []int) {
	return file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescGZIP(), []int{4}
}

func (x *DeallocatePodIPRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DeallocatePodIPRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *DeallocatePodIPRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DeallocatePodIPRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *DeallocatePodIPRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

// DeallocatePodIPResponse represents the result of a pod IP deallocation request.
// An empty message is returned on success; RPC errors are used to indicate failure.
type DeallocatePodIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeallocatePodIPResponse) Reset() {
	*x = DeallocatePodIPResponse{}
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeallocatePodIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeallocatePodIPResponse) ProtoMessage() {}

func (x *DeallocatePodIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeallocatePodIPResponse.ProtoReflect.Descriptor instead.
func (*DeallocatePodIPResponse) Descriptor() ([]byte, []int) {
	return file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescGZIP(), []int{5}
}

// CheckPodIPRequest contains the parameters required to check a pod IP allocation.
type CheckPodIPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network is the name of the network.
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// interface_name is the name of the pod interface.
	InterfaceName string `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// container_id is the id of the pod container.
	ContainerId string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// pod_name is the name of the pod. This is for logging purposes.
	PodName string `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// pod_namespace is the namespace of the pod. This is for logging purposes.
	PodNamespace  string `protobuf:"bytes,5,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPodIPRequest) Reset() {
	*x = CheckPodIPRequest{}
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPodIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPodIPRequest) ProtoMessage() {}

func (x *CheckPodIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPodIPRequest.ProtoReflect.Descriptor instead.
func (*CheckPodIPRequest) Descriptor() ([]byte, []int) {
	return file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPodIPRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CheckPodIPRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *CheckPodIPRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CheckPodIPRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *CheckPodIPRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

// CheckPodIPResponse indicates the result of the check operation.
// An empty message is returned on success; RPC errors are used to indicate failure.
type CheckPodIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPodIPResponse) Reset() {
	*x = CheckPodIPResponse{}
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPodIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPodIPResponse) ProtoMessage() {}

func (x *CheckPodIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPodIPResponse.ProtoReflect.Descriptor instead.
func (*CheckPodIPResponse) Descriptor() ([]byte, []int) {
	return file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescGZIP(), []int{7}
}

var File_metis_api_adaptiveipam_v1_adaptiveipam_proto protoreflect.FileDescriptor

const file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDesc = "" +
	"\n" +
	",metis/api/adaptiveipam/v1/adaptiveipam.proto\x12\x0fadaptiveipam.v1\"~\n" +
	"\bIPConfig\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12(\n" +
	"\x10initial_pod_cidr\x18\x03 \x01(\tR\x0einitialPodCidr\"\xe8\x01\n" +
	"\x14AllocatePodIPRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12:\n" +
	"\vipv4_config\x18\x02 \x01(\v2\x19.adaptiveipam.v1.IPConfigR\n" +
	"ipv4Config\x12:\n" +
	"\vipv6_config\x18\x03 \x01(\v2\x19.adaptiveipam.v1.IPConfigR\n" +
	"ipv6Config\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x05 \x01(\tR\fpodNamespace\":\n" +
	"\x05PodIP\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\"o\n" +
	"\x15AllocatePodIPResponse\x12*\n" +
	"\x04ipv4\x18\x01 \x01(\v2\x16.adaptiveipam.v1.PodIPR\x04ipv4\x12*\n" +
	"\x04ipv6\x18\x02 \x01(\v2\x16.adaptiveipam.v1.PodIPR\x04ipv6\"\xbc\x01\n" +
	"\x16DeallocatePodIPRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x05 \x01(\tR\fpodNamespace\"\x19\n" +
	"\x17DeallocatePodIPResponse\"\xb7\x01\n" +
	"\x11CheckPodIPRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x05 \x01(\tR\fpodNamespace\"\x14\n" +
	"\x12CheckPodIPResponse2\xab\x02\n" +
	"\fAdaptiveIpam\x12^\n" +
	"\rAllocatePodIP\x12%.adaptiveipam.v1.AllocatePodIPRequest\x1a&.adaptiveipam.v1.AllocatePodIPResponse\x12d\n" +
	"\x0fDeallocatePodIP\x12'.adaptiveipam.v1.DeallocatePodIPRequest\x1a(.adaptiveipam.v1.DeallocatePodIPResponse\x12U\n" +
	"\n" +
	"CheckPodIP\x12\".adaptiveipam.v1.CheckPodIPRequest\x1a#.adaptiveipam.v1.CheckPodIPResponseB/Z-k8s.io/metis/api/adaptiveipam/v1;adaptiveipamb\x06proto3"

var (
	file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescOnce sync.Once
	file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescData []byte
)

func file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescGZIP() []byte {
	file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescOnce.Do(func() {
		file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDesc), len(file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDesc)))
	})
	return file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDescData
}

var file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_metis_api_adaptiveipam_v1_adaptiveipam_proto_goTypes = []any{
	(*IPConfig)(nil),                // 0: adaptiveipam.v1.IPConfig
	(*AllocatePodIPRequest)(nil),    // 1: adaptiveipam.v1.AllocatePodIPRequest
	(*PodIP)(nil),                   // 2: adaptiveipam.v1.PodIP
	(*AllocatePodIPResponse)(nil),   // 3: adaptiveipam.v1.AllocatePodIPResponse
	(*DeallocatePodIPRequest)(nil),  // 4: adaptiveipam.v1.DeallocatePodIPRequest
	(*DeallocatePodIPResponse)(nil), // 5: adaptiveipam.v1.DeallocatePodIPResponse
	(*CheckPodIPRequest)(nil),       // 6: adaptiveipam.v1.CheckPodIPRequest
	(*CheckPodIPResponse)(nil),      // 7: adaptiveipam.v1.CheckPodIPResponse
}
var file_metis_api_adaptiveipam_v1_adaptiveipam_proto_depIdxs = []int32{
	0, // 0: adaptiveipam.v1.AllocatePodIPRequest.ipv4_config:type_name -> adaptiveipam.v1.IPConfig
	0, // 1: adaptiveipam.v1.AllocatePodIPRequest.ipv6_config:type_name -> adaptiveipam.v1.IPConfig
	2, // 2: adaptiveipam.v1.AllocatePodIPResponse.ipv4:type_name -> adaptiveipam.v1.PodIP
	2, // 3: adaptiveipam.v1.AllocatePodIPResponse.ipv6:type_name -> adaptiveipam.v1.PodIP
	1, // 4: adaptiveipam.v1.AdaptiveIpam.AllocatePodIP:input_type -> adaptiveipam.v1.AllocatePodIPRequest
	4, // 5: adaptiveipam.v1.AdaptiveIpam.DeallocatePodIP:input_type -> adaptiveipam.v1.DeallocatePodIPRequest
	6, // 6: adaptiveipam.v1.AdaptiveIpam.CheckPodIP:input_type -> adaptiveipam.v1.CheckPodIPRequest
	3, // 7: adaptiveipam.v1.AdaptiveIpam.AllocatePodIP:output_type -> adaptiveipam.v1.AllocatePodIPResponse
	5, // 8: adaptiveipam.v1.AdaptiveIpam.DeallocatePodIP:output_type -> adaptiveipam.v1.DeallocatePodIPResponse
	7, // 9: adaptiveipam.v1.AdaptiveIpam.CheckPodIP:output_type -> adaptiveipam.v1.CheckPodIPResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metis_api_adaptiveipam_v1_adaptiveipam_proto_init() }
func file_metis_api_adaptiveipam_v1_adaptiveipam_proto_init() {
	if File_metis_api_adaptiveipam_v1_adaptiveipam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDesc), len(file_metis_api_adaptiveipam_v1_adaptiveipam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metis_api_adaptiveipam_v1_adaptiveipam_proto_goTypes,
		DependencyIndexes: file_metis_api_adaptiveipam_v1_adaptiveipam_proto_depIdxs,
		MessageInfos:      file_metis_api_adaptiveipam_v1_adaptiveipam_proto_msgTypes,
	}.Build()
	File_metis_api_adaptiveipam_v1_adaptiveipam_proto = out.File
	file_metis_api_adaptiveipam_v1_adaptiveipam_proto_goTypes = nil
	file_metis_api_adaptiveipam_v1_adaptiveipam_proto_depIdxs = nil
}
