// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: metis/api/adaptiveipam/v1/adaptiveipam.proto

package adaptiveipam

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdaptiveIpam_AllocatePodIP_FullMethodName   = "/adaptiveipam.v1.AdaptiveIpam/AllocatePodIP"
	AdaptiveIpam_DeallocatePodIP_FullMethodName = "/adaptiveipam.v1.AdaptiveIpam/DeallocatePodIP"
)

// AdaptiveIpamClient is the client API for AdaptiveIpam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdaptiveIpam serves the request for cluster wide pod IP allocation. The IP
// returned is from the initial cidr range, or dynamically fetched from cloud provider.
type AdaptiveIpamClient interface {
	// AllocatePodIP allocates a pod IP based on the provided configuration.
	AllocatePodIP(ctx context.Context, in *AllocatePodIPRequest, opts ...grpc.CallOption) (*AllocatePodIPResponse, error)
	// DeallocatePodIP releases a previously allocated pod IP.
	// The completion of this RPC indicates the pod IP is released for the pod.
	// The IP can be reused for other pods on the node level, or will be eventually
	// released at the cloud provider.
	DeallocatePodIP(ctx context.Context, in *DeallocatePodIPRequest, opts ...grpc.CallOption) (*DeallocatePodIPResponse, error)
}

type adaptiveIpamClient struct {
	cc grpc.ClientConnInterface
}

func NewAdaptiveIpamClient(cc grpc.ClientConnInterface) AdaptiveIpamClient {
	return &adaptiveIpamClient{cc}
}

func (c *adaptiveIpamClient) AllocatePodIP(ctx context.Context, in *AllocatePodIPRequest, opts ...grpc.CallOption) (*AllocatePodIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocatePodIPResponse)
	err := c.cc.Invoke(ctx, AdaptiveIpam_AllocatePodIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adaptiveIpamClient) DeallocatePodIP(ctx context.Context, in *DeallocatePodIPRequest, opts ...grpc.CallOption) (*DeallocatePodIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeallocatePodIPResponse)
	err := c.cc.Invoke(ctx, AdaptiveIpam_DeallocatePodIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdaptiveIpamServer is the server API for AdaptiveIpam service.
// All implementations must embed UnimplementedAdaptiveIpamServer
// for forward compatibility.
//
// AdaptiveIpam serves the request for cluster wide pod IP allocation. The IP
// returned is from the initial cidr range, or dynamically fetched from cloud provider.
type AdaptiveIpamServer interface {
	// AllocatePodIP allocates a pod IP based on the provided configuration.
	AllocatePodIP(context.Context, *AllocatePodIPRequest) (*AllocatePodIPResponse, error)
	// DeallocatePodIP releases a previously allocated pod IP.
	// The completion of this RPC indicates the pod IP is released for the pod.
	// The IP can be reused for other pods on the node level, or will be eventually
	// released at the cloud provider.
	DeallocatePodIP(context.Context, *DeallocatePodIPRequest) (*DeallocatePodIPResponse, error)
	mustEmbedUnimplementedAdaptiveIpamServer()
}

// UnimplementedAdaptiveIpamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdaptiveIpamServer struct{}

func (UnimplementedAdaptiveIpamServer) AllocatePodIP(context.Context, *AllocatePodIPRequest) (*AllocatePodIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocatePodIP not implemented")
}
func (UnimplementedAdaptiveIpamServer) DeallocatePodIP(context.Context, *DeallocatePodIPRequest) (*DeallocatePodIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeallocatePodIP not implemented")
}
func (UnimplementedAdaptiveIpamServer) mustEmbedUnimplementedAdaptiveIpamServer() {}
func (UnimplementedAdaptiveIpamServer) testEmbeddedByValue()                      {}

// UnsafeAdaptiveIpamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdaptiveIpamServer will
// result in compilation errors.
type UnsafeAdaptiveIpamServer interface {
	mustEmbedUnimplementedAdaptiveIpamServer()
}

func RegisterAdaptiveIpamServer(s grpc.ServiceRegistrar, srv AdaptiveIpamServer) {
	// If the following call panics, it indicates UnimplementedAdaptiveIpamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdaptiveIpam_ServiceDesc, srv)
}

func _AdaptiveIpam_AllocatePodIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocatePodIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdaptiveIpamServer).AllocatePodIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdaptiveIpam_AllocatePodIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdaptiveIpamServer).AllocatePodIP(ctx, req.(*AllocatePodIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdaptiveIpam_DeallocatePodIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeallocatePodIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdaptiveIpamServer).DeallocatePodIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdaptiveIpam_DeallocatePodIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdaptiveIpamServer).DeallocatePodIP(ctx, req.(*DeallocatePodIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdaptiveIpam_ServiceDesc is the grpc.ServiceDesc for AdaptiveIpam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdaptiveIpam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adaptiveipam.v1.AdaptiveIpam",
	HandlerType: (*AdaptiveIpamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocatePodIP",
			Handler:    _AdaptiveIpam_AllocatePodIP_Handler,
		},
		{
			MethodName: "DeallocatePodIP",
			Handler:    _AdaptiveIpam_DeallocatePodIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metis/api/adaptiveipam/v1/adaptiveipam.proto",
}
