load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["register.go"],
    importpath = "k8s.io/cloud-provider-gcp/pkg/apis/firewall",
    visibility = ["//visibility:public"],
)
