load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "serviceaccounts",
    srcs = ["types.go"],
    importpath = "k8s.io/cloud-provider-gcp/cmd/gcp-controller-manager/dpwi/serviceaccounts",
    visibility = ["//visibility:public"],
)
