/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
	networkv1 "k8s.io/cloud-provider-gcp/crd/apis/network/v1"
	scheme "k8s.io/cloud-provider-gcp/crd/client/network/clientset/versioned/scheme"
)

// GKENetworkParamsListsGetter has a method to return a GKENetworkParamsListInterface.
// A group's client should implement this interface.
type GKENetworkParamsListsGetter interface {
	GKENetworkParamsLists() GKENetworkParamsListInterface
}

// GKENetworkParamsListInterface has methods to work with GKENetworkParamsList resources.
type GKENetworkParamsListInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*networkv1.GKENetworkParamsList, error)
	GKENetworkParamsListExpansion
}

// gKENetworkParamsLists implements GKENetworkParamsListInterface
type gKENetworkParamsLists struct {
	client rest.Interface
}

// newGKENetworkParamsLists returns a GKENetworkParamsLists
func newGKENetworkParamsLists(c *NetworkingV1Client) *gKENetworkParamsLists {
	return &gKENetworkParamsLists{
		client: c.RESTClient(),
	}
}

// Get takes name of the gKENetworkParamsList, and returns the corresponding gKENetworkParamsList object, and an error if there is any.
func (c *gKENetworkParamsLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *networkv1.GKENetworkParamsList, err error) {
	result = &networkv1.GKENetworkParamsList{}
	err = c.client.Get().
		Resource("gkenetworkparamslists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}
