#!/usr/bin/env bash

# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "${REPO_ROOT}"

# 1. Project Lifecycle Management (Boskos)
if [[ -z "${GCP_PROJECT:-}" ]]; then
    echo "GCP_PROJECT not set, acquiring project from boskos"
    source test/boskos.sh
    acquire_project
    export GCP_PROJECT="${PROJECT}"
    trap cleanup_boskos EXIT
else
    export GCP_PROJECT
fi

# 2. Cluster Lifecycle Management
export KOPS_CLUSTER_NAME="${CLUSTER_NAME:-kops-simple.k8s.local}"
make kops-up

# 3. Define cleanup function
function cleanup {
  local exit_status=$?
  if [[ "${DELETE_CLUSTER:-true}" == "true" ]]; then
    make kops-down
  fi
  if [[ -n "${BOSKOS_HEARTBEAT_PID:-}" ]]; then
    source test/boskos.sh
    cleanup_boskos || echo "Warning: cleanup_boskos failed"
  fi
  exit "${exit_status}"
}
trap cleanup EXIT

# 4. Test Execution
export K8S_VERSION=$(make print-k8s-version)
make kops-e2e-test KOPS_CLUSTER_NAME="${KOPS_CLUSTER_NAME}"

# 5. Teardown
if [[ "${DELETE_CLUSTER:-true}" == "true" ]]; then
  make kops-down
  DELETE_CLUSTER=false # Prevent redundant deletion in trap
fi
