#!/usr/bin/env bash

# Copyright 2023 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -x

source $(git rev-parse --show-toplevel)/tools/common

# TODO: Don't override tag, drop --snapshot, drop --clean
GORELEASER_CURRENT_TAG=v0.0.1 go run github.com/goreleaser/goreleaser@v1.20.0 build --snapshot  --clean
