#!/usr/bin/env bash

# Copyright 2023 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -x

source $(git rev-parse --show-toplevel)/tools/common

# IMAGE_REPO is used to upload images
if [[ -z "${IMAGE_REPO:-}" ]]; then
  echo "IMAGE_REPO must be set"
  exit 1
fi
echo "IMAGE_REPO=${IMAGE_REPO}"
export KO_DOCKER_REPO="${IMAGE_REPO}"

# We set the tag if we want to build and push the image
CCM_IMAGE_TAG=""
GCM_IMAGE_TAG=""

# Parse all the git tags
tags=()
while IFS= read -r tag
do
  tags+=( "${tag}" )
  echo "Found tag ${tag}"

  # Look for component-specific tags, like ccm/v1.2.3
  if [[ "$tag" == *"/"* ]]; then
    component=$(dirname "${tag}")
    image_tag=$(basename "${tag}")
    if [[ "${component}" == "ccm" ]]; then
      CCM_IMAGE_TAG="${image_tag}"
    elif [[ "${component}" == "gcm" ]]; then
      GCM_IMAGE_TAG="${image_tag}"
    else
      echo "Unknown component found in tag ${tag}, ignoring"
    fi
  fi
done < <(git tag --points-at HEAD)

# If no direct tags, construct a tag from git and build all components
if [[ ${#tags[@]} -eq 0 ]]; then
  # We default to a unique value that combines the sha and the (real) build date
  image_tag=$(date +%Y%m%dT%H%M%S)-$(git rev-parse --short HEAD)
  CCM_IMAGE_TAG="${image_tag}"
  GCM_IMAGE_TAG="${image_tag}"
fi

if [[ -n "${CCM_IMAGE_TAG}" ]]; then
  go run github.com/google/ko@v0.14.1 build --tags=${CCM_IMAGE_TAG} --base-import-paths --push=true ./cmd/cloud-controller-manager/
else
  echo "Skipping CCM build, because no relevant tag found"
fi

if [[ -n "${GCM_IMAGE_TAG}" ]]; then
  go run github.com/google/ko@v0.14.1 build --tags=${GCM_IMAGE_TAG} --base-import-paths --push=true ./cmd/gcp-controller-manager/
else
  echo "Skipping GCM build, because no relevant tag found"
fi
