name: Dependabot Go Work Sync

on:
  pull_request:
    paths:
      - '**/go.mod'
      - '**/go.sum'

permissions:
  contents: write

jobs:
  go-work-sync:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: 'go.work'

      - name: Sync Go Workspace
        run: ./tools/update_vendor.sh
        
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          shopt -s globstar
          git add go.work go.work.sum **/go.mod **/go.sum vendor/
          # Only commit if there are actual changes
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: sync go workspace and vendor"
          git push