name: Metis GLIBC Floor Test

on:
  pull_request:
    paths:
      - 'metis/**'

jobs:
  native-execution-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test GLIBC compatibility
        run: |
          cd metis
          make test-glibc-floor
