name: Tag CCM

on:
  push:
    branches:
      - 'release-1.*'
    paths-ignore:
      - 'cmd/auth-provider-gcp/**'
      - 'cmd/gke-gcloud-auth-plugin/**'

jobs:
  tag-ccm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run auto-tag script
        env:
          DRY_RUN: "false"
          FORCE_BRANCH: ${{ github.ref_name }}
          COMPONENT_PREFIX: ""
        run: ./tools/auto-tag.sh
